spring:
  datasource:
    url: jdbc:mysql://mysql-min:3306/mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    username: reader
    password: 123456
  elasticsearch:
    rest:
      uris: http://localhost:9200
logging:
  level:
    root: info
    com.dunshan.mall: debug
logstash:
  host: localhost
